### ISSUE TITLE
Installation: The prebuilt binary and `stack setup` both fail on NixOS.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [mikesol/wagsi#8]
I installed PureScript, npm and VSCode via the NixOS repo, and installed a few of the PureScript extensions from within VSCode. Here are the versions of some software on my system:
```
jeff@jbb-dell:wagsi$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.4
jeff@jbb-dell:wagsi$ stack --version
2.7.1 x86_64 hpack-0.34.4
jeff@jbb-dell:wagsi$ npm --version
6.14.15
jeff@jbb-dell:wagsi$ purs --version
0.14.0
jeff@jbb-dell:wagsi$ git log    # the version of Wagsi I checked out
commit 80932edacacf9d3e1c5012d59e5ebcc7d34288eb (HEAD -> main, origin/main, origin/HEAD)
```

When I try to open a shell in VSCode I get the error `The terminal process failed to launch: Path to shell executable "bash" is not a file or a symlink.` (Is anyone using wagsi in Emacs? I'd prefer that to VSCode.) So I ran `npm install && npm start` from a separate terminal application (Konsole), whereupon I got this:
```
jeff@jbb-dell:wagsi$ npm install && npm start
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> purescript@0.14.3 postinstall /home/jeff/code/music/wagsi/node_modules/purescript
> install-purescript --purs-ver=0.14.3

✔ Check if a prebuilt 0.14.3 binary is provided for linux
✔ Download the prebuilt PureScript binary (6s)
✖ Verify the prebuilt binary works correctly
  /home/jeff/code/music/wagsi/node_modules/purescript/purs.bin --version
  Error: spawn /home/jeff/code/music/wagsi/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
▬ Save the downloaded binary to the npm cache directory

↓ Fallback: building from source

✔ Check if 'stack' command is available
        2.7.1 found at /run/current-system/sw/bin/stack
✔ Download the PureScript 0.14.3 source (2s)
✖ Ensure the appropriate GHC is installed (396ms)
  stack setup
  Error: Command failed with exit code 1 (EPERM): stack --allow-different-user setup
    at makeError (/home/jeff/code/music/wagsi/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/jeff/code/music/wagsi/node_modules/execa/index.js:112:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
▬ Build a binary from source
▬ Save the built binary to the npm cache directory

npm WARN tailwindcss@2.1.2 requires a peer of autoprefixer@^10.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN wagsi@ No repository field.
npm WARN wagsi@ No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.14.3 postinstall: `install-purescript --purs-ver=0.14.3`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the purescript@0.14.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeff/.npm/_logs/2021-10-09T18_13_51_013Z-debug.log
jeff@jbb-dell:wagsi$
```

**Comment by mikesol** [comment]
Hi @JeffreyBenjaminBrown ! Sorry I'm late to getting to this - you are the first person to have filed an issue on this repo (congrats! :confetti_ball: ). I'll set up notifications to give more speedy replies and I'll look into this straight away.

**Comment by JeffreyBenjaminBrown** [comment]
If I'm unable to run `npm install && npm run` in Bash, should I have reason to expect it to work in Emacs?

**Comment by mikesol** [comment]
Could you edit `package.json`, remove spago & purescript and see if it works? The only issue is that if `purs` is at `0.14.0` in your nix distro it could have a couple bugs that would prevent compilation, but it's possible that 0.14.0 works out-of-the-box.

Would you be ok using `nix-shell` if I included a `shell.nix` file? I can write separate install instructions for that path if it's easier.

**Comment by mikesol** [comment]
My nix-foo is at white-belt level, so it's hard for me to know if the bug is coming from the `nix` setup or `spago` or something else entirely. My guess would be that the bug here is from `spago` and not `purescript, as `spago` deals with package-sets whereas `purescript` doesn't. `spago` is having trouble downloading a package set from GitHub, which may mean that GitHub was down at the moment you were downloading the file? Seems like a long shot, but if you re-run then that can test that hypothesis.

If it keeps stalling there, I can try the `nix-shell` route: it's what we use for purescript registry development and it has served us well so far.

**Comment by JeffreyBenjaminBrown** [comment]
Would it matter that my Spago is at version 0.20.2?

**Comment by mikesol** [comment]
Indeed, I think we're really close! The skipping dependency stuff is npm skipping over node-only stuff, which is fine as the build is for the browser.

If you're able to install https://github.com/purescript-emacs/psc-ide-emacs in emacs, then the only thing left should be pointing it to the `purs` executable. In `nix-shell`, I think you can use `whereis purs` or `which purs` to find this path (it'll be something long and incomprehensible in a nix directory). This can be used to set the `psc-ide-purs-executable` setting: https://github.com/purescript-emacs/psc-ide-emacs/blob/ce97d719458ea099b40c02f05b6609601c727e66/psc-ide.el#L73. There are a few other settings in there that may be useful (I've never used it so I'm not familiar with the config). You can also ping folks on the PreScript Discord `#help-tools` channel - there are several emacs users there.

Let me know if that works!

**Comment by JeffreyBenjaminBrown** [comment]
Thanks, Mike!

**Comment by thomashoneyman** [comment]
I don't use emacs, so I hope I'm still able to help a little, but here are a couple things that may help:

* The `psc-ide` server is part of the `purs` compiler, so you don't need to install anything separately. With `purs` in your path you shouldn't have to point anything at its location in the Nix store (as soon as you update `purs` it'll break if you do that)
* The most common way to use PureScript tooling like Spago, the compiler, etc. is via the `easy-purescript-nix` project, as is done in Mike's new `default.nix`. I'm not currently on NixOS, but when I was I installed all tooling that way instead of via `nixpkgs`, as the nixpkgs version of PureScript is either the library or typically long out of date 😆 
* I'm not sure if you're already using this, but there's a "purescript mode" for emacs: https://github.com/purescript-emacs/purescript-mode

**Comment by mikesol** [comment]
Fabrizio gave a few good ideas here: https://github.com/purescript/spago/issues/825#issuecomment-947543496

**Comment by mikesol** [comment]
The next step once it works is:

```bash
npm install --no-optional && npm start
```

Eventually a browser should pop up!

**Comment by mikesol** [comment]
@JeffreyBenjaminBrown , are you still having this issue?

**Comment by JeffreyBenjaminBrown** [comment]
It almost works! When I run `npm install && npm start` it now installs, and brings up a browser tab with, eventually, a `start audio` button to click. When I click that some more text appears but I don't hear anything. I haven't started Qjackctl (I assume it's not needed) and I'm able to get sound on Youtube.

I assume the reason it's working is that nixpkgs is more up to date now. I upgraded to NixOS 21.11 recently. In case it's of interest to some future NixOS user, my [configuration is here](https://github.com/JeffreyBenjaminBrown/nixos-experiments/tree/9bce253f5fa84c0b83b894521bd4c4cde8602aa1/config).

**Comment by mikesol** [comment]
Sweet, you're a stone's throw away from audio!
A couple questions:
- Is there anything in the browser console indicating an error after you click on start?
- Are you able to play any of the examples on [this site](https://github.com/mdn/webaudio-examples/)?
- Are you able to play any of the examples on [this site](https://mikesol.github.io/wagsi)? After you select an example on the left, you have to scroll down to start it (the list of examples is long, so it pushes everything down on the page).

Thanks! We're close to getting it to work!

**Comment by JeffreyBenjaminBrown** [comment]
Oh hi there :)

If I open up the Javascript console from the Wagsi browser tab, then before pressing start I see these errors:
```
Found an initial wag 🐶
index.js:29 Found initial code 📦
log.js:24 [HMR] Waiting for update signal from WDS...
foreign.js:2 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
exports.context @ foreign.js:2
:8080/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:49 [WDS] Hot Module Replacement enabled.
index.js:53 [WDS] Live Reloading enabled.
DevTools failed to load source map: Could not load content for webpack://wagsi/node_modules/sockjs-client/dist/sockjs.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

When I then press start I see nothing new in the console, and no other indication of error, but I hear nothing.

From the first site you posted, "make white noise" sure as hell worked:
   https://mdn.github.io/webaudio-examples/audio-buffer/
From the second one you posted, "drone with delay" also worked.
   https://mikesol.github.io/wagsi/#Drone%20with%20delay

**Comment by mikesol** [comment]
That is an error we used to get but haven't for a while. Have you git-pulled the most recent changes? Also, could you let me know what browser(s) you're using? All of the major ones should theoretically work, but there could be some issues I've overlooked. Thanks!

**Comment by JeffreyBenjaminBrown** [comment]
Thanks!

I redefined node to be the package `nodejs-17_x" and rebuilt my system. Now things seem pretty up to date:
```
jeff@jbb-dell:wagsi$ npm --version
8.3.0
jeff@jbb-dell:wagsi$ spago --version
0.20.2
jeff@jbb-dell:wagsi$ purs --version
0.14.5
jeff@jbb-dell:wagsi$ git remote -v
origin  https://github.com/mikesol/wagsi (fetch)
origin  https://github.com/mikesol/wagsi (push)
jeff@jbb-dell:wagsi$ git log
commit 9bb64f29b9ccf464c2d639e622d590ad3f5971a7 (HEAD -> main, origin/main, origin/HEAD)
Author: Mike Solomon <mike@wavr.so>
Date:   Sun Jan 16 19:35:23 2022 +0200

    Resets wagsi
```

And now wagsi won't build:
```
jeff@jbb-dell:wagsi$ npm install && npm start
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'amqplib@0.5.2',
npm WARN EBADENGINE   required: { node: '>=0.8 <=9' },
npm WARN EBADENGINE   current: { node: 'v17.3.1', npm: '8.3.0' }
npm WARN EBADENGINE }

up to date, audited 1098 packages in 39s

73 packages are looking for funding
  run `npm fund` for details

57 vulnerabilities (2 low, 47 moderate, 4 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice
npm notice New patch version of npm available! 8.3.0 -> 8.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.1
npm notice Run npm install -g npm@8.3.1 to update!
npm notice

> start
> spago install && spago build && webpack serve --mode=development --open

sh: line 1: /home/jeff/code/music/wagsi/node_modules/.bin/spago: No such file or directory
```

I can't remember which browser it opened in when it opened, before I rebuilt my system, but it was probably Brave. My browsers are Brave, Chrome and FIrefox.
